### ISSUE TITLE
Custom bat themes

### ISSUE THREAD

**Issue by stijn577** [cptpiepmatz/nu-plugin-highlight#10]
Hey, so this is a really nice project, I was wondering if the code could be changed so any theme valid for bat is valid for highlight (now it only has the default themes shipped with bat).

After a bit of digging I edited your project so now cached themes from bat are also useable.

![image](https://github.com/cptpiepmatz/nu-plugin-highlight/assets/120060947/fa9770c9-7dee-4537-a18e-f2743d7224d0)
![image](https://github.com/cptpiepmatz/nu-plugin-highlight/assets/120060947/d1557b57-7d06-48e9-bd3c-4a313745cc8c)

basically all that needs to change is the Highlighter new() implementation. idk if bat caches without explicitly calling bat cache --build, could cause crashes. But can be fixed I guess by always running bat cache --build in another Command(...).

```rust
impl Highlighter {
    // Creates a new instance of the Highlighter.
    pub fn new() -> Self {
        // find bat cache directory and parse to string
        let output = String::from_utf8(
            std::process::Command::new("bat")
                .arg("--cache-dir")
                .output()
                .expect("bat not found")
                .stdout
        )
        .unwrap();

        let path = PathBuf::from(output.trim_end());
        let path = path.as_path();
        Highlighter {
            highlighting_assets: HighlightingAssets::from_cache(path).unwrap()
        }
    }
    // ...
}
 ```
 
 Otherwise nice project man, was really struggling wanting to pipe nu stuff into bat properly, this does what i need it to, 😁❤

**Comment by cptpiepmatz** [comment]
I don't want to use bat's cache (as I am not using bat myself). But with the new config system that nu provides, we could probably just add something in the plugin config that allows loading themes. Can you refer to me how themes are used for bat? I guess they also have some kind of serialized file, no?

**Comment by stijn577** [comment]
bat uses .tmTheme files, it seems syntect has a struct wrapper for a parsed .tmTheme file, so it's literally the same as the syntect Theme structs. There is this function https://docs.rs/syntect/5.0.0/syntect/highlighting/struct.ThemeSet.html#method.load_from_reader

it should allow you to create a BTreeMap of Strings with matching themes from themes in a certain directory.
if you add this Tree as a field to the HighLighter, it doesn't seems like it should be pretty straightforward to modify the code from there. 
```rust
    pub fn new() -> Self {
        let assets = HighlightingAssets::from_binary();
        let mut assets = assets
            .themes()
            .map(|name| {
                let s = name.to_string();
                let t = assets.get_theme(name).to_owned();
                (s, t)
            })
            .collect::<BTreeMap<String, Theme>>();
        
        // path as $env variable ?, if path exists add else just use assets
        if let Ok(list) = ThemeSet::load_from_folder("THEMESFOLDER") {
            assets.extend(list.themes);
        }

        HighLighter {
            assets
        }
    }
```
and probably make the default $env var the default bat config dir ./themes

**Comment by stijn577** [comment]
Hey,

I've dug a little deeper and that won't suffice (doesn't allow picking up the syntax etc.), I tried some stuff and I'm just finalsing some stuff for a PR. It takes the bat.exe into account so it doesn't cause issues with cache versions. I'm just finalising working through some possible edge cases and making it give better info to the user by logging.
