### ISSUE TITLE
error in nushell 0.97.2

### ISSUE THREAD

**Issue by kurokirasama** [cptpiepmatz/nu-plugin-highlight#13]
Hey, I just updated nushell to 0.97.2 and the plugin to v1.2.2+0.97.1, but when doing `plugin add ~/.cargo/bin/nu_plugin_net` i get this error:

```
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `description`
```

**Comment by cptpiepmatz** [comment]
https://github.com/nushell/nushell/pull/13598 introduced a breaking change for commands. As `0.97.2` is not a published release, I won't publish something against that. But I created a `next` branch that builds against the `main` branch of nushell directly. That should work for you.

I'm keeping this open until the next release of nushell.

**Comment by cptpiepmatz** [comment]
version 1.3.1 fixes that
