### ISSUE TITLE
Compile for latest version

### ISSUE THREAD

**Issue by Stef16Robbe** [cptpiepmatz/nu-plugin-highlight#14]
Hi there,

Thanks for making this awesome plugin ^^. It looks like the compiled version is outdated at the moment:

```nu
~> plugin add /Users/srobbe/.cargo/bin/nu_plugin_highlight
Error:
  × Failed to send plugin call to `highlight`
  help: try loading the plugin again with `plugin use 'highlight'`

Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin `highlight` is compiled for nushell version 0.100.0, which is not compatible with version 0.101.0
```

Is it as simple as updating the `nu` Cargo dependencies?

**Comment by cptpiepmatz** [comment]
Most often you just need to update the nu dependencies. If that is not enough, you have to check the changelog. Often it has a [notes for plugin developers](https://www.nushell.sh/blog/2024-12-24-nushell_0_101_0.html#notes-for-plugin-developers-toc) section that explains changes for plugins. This release did not break anything for my plugin, so I just released [v1.4.2+0.101.0](https://github.com/cptpiepmatz/nu-plugin-highlight/releases/tag/v1.4.2%2B0.101.0).
